---
title: "Lika working file"
author: "Lika Mikhelashvili"
date: "2022-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
library(stringr)
library("htmltools")
library("xml2")
library(tidyverse)
library(readr)
#install.packages("rjson")
library(rjson)
```

```{r}
##function returns the downloaded data frame. the user has to assign the data frame to an object and import it into the r studio environment. 
get_gov_file <- function(name, type){
  prefix <- "https://catalog.data.gov/dataset"
  #Specific name needs to be lowercase and with dashes between words
  specific <- tolower(name)
  specific <- gsub(" ", "-", specific)
  # paste the prefix and name together with a slash and no spaces
  full_url <- paste0(prefix,"/", specific, sep = "")
  #get HTML of the name given
  html <- read_html(full_url)

  # creating the XML command to find the data they are looking for
  first <- ".//a[@data-format='"
  last <- "']"
  typeTogether <- paste0(first, type, last)

  #https://stackoverflow.com/questions/45256789/get-value-from-xml-with-r-by-attribute
  #find the xml that is a link with data-format attribute of the type asked
  final <- xml_find_all(html, typeTogether)
  final <- html_attr(final, 'href')
  
  filename <- str_c(name, ".", type)
  
  download.file(url = final, destfile = filename, overwrite = T)
  
  if(type == "csv"){
    return(read_csv(filename))
  } else if(type == "json"){
    #https://www.educative.io/answer\s/how-to-read-json-files-in-r
    myData <- fromJSON(file = filename)
    json_data_frame <- as.data.frame(myData)
    return(json_data_frame)
  }
  #return(final)
}

#Code to Deal with JSON Files
#temp <- unlist(myData$data) %>% matrix(nrow = 1390, byrow=TRUE) %>% as.data.frame()
```


```{r}
name <- "Lottery Powerball Winning Numbers Beginning 2010"
# assignment happens like this:
my_data <- get_gov_file(name, "json")
```



THIS FUNCTION BELOW DOES NOT WORK FOR ME
```{r}
## function downloads and automatically imports the file onto the R studio environment
download_import_gov_file <- function(name, type){
  prefix <- "https://catalog.data.gov/dataset"
  #Specific name needs to be lowercase and with dashes between words
  specific <- tolower(name)
  specific <- gsub(" ", "-", specific)
  # paste the prefix and name together with a slash and no spaces
  full_url <- paste0(prefix,"/", specific, sep = "")
  #get HTML of the name given
  html <- read_html(full_url)

  # creating the XML command to find the data they are looking for
  first <- ".//a[@data-format='"
  last <- "']"
  typeTogether <- paste0(first, type, last)

  #https://stackoverflow.com/questions/45256789/get-value-from-xml-with-r-by-attribute
  #find the xml that is a link with data-format attribute of the type asked
  final <- xml_find_all(html, typeTogether)
  final <- html_attr(final, 'href')

  download.file(url = final, destfile = str_c(name, ".", type), overwrite = T)
  
  assign(str_c(name, ".", type), read_csv(str_c(name, ".", type)))
  #return(read_csv(str_c(name, ".", type)))
  #return(final)
}
```

```{r}
name <- "Lottery Powerball Winning Numbers Beginning 2010"
# assignment happens like this:
my_data<- download_import_gov_file(name, "cvs")
```

