---
title: "Vibha Working File"
author: "Vibha Gogu"
date: "2022-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(stringr)
library("htmltools")
library("xml2")
library(readr)
```


```{r}
##function returns the downloaded data frame. the user has to assign the data frame to an object and import it into the r studio environment. 
get_gov_file <- function(name, type){
  prefix <- "https://catalog.data.gov/dataset"
  #Specific name needs to be lowercase and with dashes between words
  specific <- tolower(name)
  specific <- gsub(" ", "-", specific)
  # paste the prefix and name together with a slash and no spaces
  full_url <- paste0(prefix,"/", specific, sep = "")
  #get HTML of the name given
  tryCatch(
  expr = {html <- read_html(full_url)}, 
  error = function(e){          # Specifying error message
  message("There was an error. The dataset was not found")
        }
  )

  # creating the XML command to find the data they are looking for
  first <- ".//a[@data-format='"
  last <- "']"
  typeTogether <- paste0(first, type, last)

  #https://stackoverflow.com/questions/45256789/get-value-from-xml-with-r-by-attribute
  #find the xml that is a link with data-format attribute of the type asked
  final <- xml_find_all(html, typeTogether)
  final <- html_attr(final, 'href')
  
  filename <- str_c(name, ".", type)
  
  tryCatch(
      expr = {
        download.file(url = final, destfile = filename, overwrite = T)
        if(type == "csv"){
        return(read_csv(filename, readr::locale(encoding="latin1"), show_col_types = FALSE))
        } 
        else if(type == "json"){
        #https://www.educative.io/answer\s/how-to-read-json-files-in-r
        myData <- fromJSON(file = filename)
        json_data_frame <- as.data.frame(myData)
        return(json_data_frame)  
        }
        },
        warning = function(w){        # Specifying warning message
        message(paste0("Redirecting to this page: ", final))
        browseURL(final)
        }, 
        finally = {                   # Specifying final message
        message("tryCatch is finished.")
        }
       )

  #return(final)
}


# tryCatch(                       # Applying tryCatch
#  
#   expr = {                      # Specifying expression
#     1 + "1"
#     message("Everything was fine.")
#   },
#  
#   error = function(e){          # Specifying error message
#     message("There was an error message.")
#   },
#  
#   warning = function(w){        # Specifying warning message
#     message("There was a warning message.")
#   },
#  
#   finally = {                   # Specifying final message
#     message("tryCatch is finished.")
#   }
# )

#Code to Deal with JSON Files
#temp <- unlist(myData$data) %>% matrix(nrow = 1390, byrow=TRUE) %>% as.data.frame()
```

```{r}
browseURL("https://www.r-project.org")
```

```{r}
name <- "Feed Grains Database"
# assignment happens like this:
my_data <- get_gov_file(name, "csv")
```
To consider: Consumer Complaint Database has .csv.zip. We need to find a way to unzip the file as well. 
Need to figure out what to say when user asks to import file type that is not available. 
